var ASMAPI = Java.type('net.minecraftforge.coremod.api.ASMAPI');
var NT = ASMAPI.NumberType;
var O = Java.type('org.objectweb.asm.Opcodes');
var MethodNode = Java.type('org.objectweb.asm.tree.MethodNode');
var Label = Java.type('org.objectweb.asm.Label');
var Type = Java.type('org.objectweb.asm.Type');
var Handle = Java.type('org.objectweb.asm.Handle');
var TypePath = Java.type('org.objectweb.asm.TypePath');
var Scanner = Java.type('java.util.Scanner');
function number(s, type) {
    var scan = new Scanner(s); scan.useLocale(Java.type('java.util.Locale').ROOT);
    var n = type === NT.LONG ? scan.nextLong() : scan.nextDouble();
    scan.close(); return ASMAPI.castNumber(n, type);
}
function removeMethod(c, name, desc, count) {
    for (var i=0; i<c.methods.size(); i++) {
        var m=c.methods.get(i);
        if (m.name !== name || m.desc !== desc) continue;
        var found=0, nodes=m.instructions.toArray();
        for(var j=0;j<nodes.length;j++) if(nodes[j].getOpcode()>=0) found++;
        if(found!==count) throw new Error('Consolidation adapter mismatch '+c.name+'.'+name+': '+found+' expected '+count);
        c.methods.remove(i);return;
    }
    throw new Error('Consolidation adapter missing method '+c.name+'.'+name+desc);
}
function removeField(c, name, desc) {
    for(var i=0;i<c.fields.size();i++){var f=c.fields.get(i);if(f.name===name&&f.desc===desc){c.fields.remove(i);return;}}
    throw new Error('Consolidation adapter missing field '+c.name+'.'+name);
}

var BONS_KEY = "curios_lazy_modifier_map"; var BONS_SCRIPT = "furious8-curios.js"; var BONS_TARGET = "top.theillusivec4.curios.common.capability.CurioInventoryCapability$CurioInventoryWrapper";
// --- Bons and Furious release guard (inserted by build.py; ES5 only, Forge coremod sandbox) ---
var BONS_ENGINE_LIST = Java.type('java.util.ArrayList');
var BONS_ENGINE_SET = Java.type('java.util.HashSet');
function bonsLog(level, message) { try { ASMAPI.log(level, message); } catch (e) {} }
function bonsDisabled() {
    if (!ASMAPI.getSystemPropertyFlag('bons_and_furious.config.loaded')) {
        bonsLog('WARN', 'Bons and Furious: configuration was not loaded before ' + BONS_SCRIPT + ' transformed ' + BONS_TARGET + '; applying the optimization by default');
        return false;
    }
    return ASMAPI.getSystemPropertyFlag('bons_and_furious.disabled.' + BONS_KEY);
}
function bonsCheckMembers(c) {
    var seen = new BONS_ENGINE_SET();
    for (var i = 0; i < c.methods.size(); i++) { var m = c.methods.get(i); if (!seen.add('m ' + m.name + m.desc)) throw new Error('duplicate method ' + m.name + m.desc); }
    for (var j = 0; j < c.fields.size(); j++) { var f = c.fields.get(j); if (!seen.add('f ' + f.name + ' ' + f.desc)) throw new Error('duplicate field ' + f.name); }
}
function bonsGuarded(c, body) {
    if (bonsDisabled()) {
        bonsLog('INFO', 'Bons and Furious: ' + BONS_KEY + ' is disabled by config; ' + c.name + ' is left unchanged');
        return c;
    }
    var methods = new BONS_ENGINE_LIST(c.methods), fields = new BONS_ENGINE_LIST(c.fields);
    var interfaces = c.interfaces === null ? null : new BONS_ENGINE_LIST(c.interfaces);
    var access = c.access, superName = c.superName, signature = c.signature, version = c.version;
    try {
        var result = body(c);
        if (result !== c) throw new Error('transformer returned a different class node');
        bonsCheckMembers(c);
        bonsLog('DEBUG', 'Bons and Furious: ' + BONS_KEY + ' applied to ' + c.name);
        return c;
    } catch (e) {
        c.methods.clear(); c.methods.addAll(methods);
        c.fields.clear(); c.fields.addAll(fields);
        if (interfaces !== null) { c.interfaces.clear(); c.interfaces.addAll(interfaces); }
        c.access = access; c.superName = superName; c.signature = signature; c.version = version;
        bonsLog('WARN', 'Bons and Furious: ' + BONS_KEY + ' skipped for ' + c.name + ' because the installed class does not match the supported version (' + e + '); the class is left unchanged');
        return c;
    }
}
// --- end of release guard ---

function initializeCoreMod(){return {patch:{target:{type:"CLASS",name:"top.theillusivec4.curios.common.capability.CurioInventoryCapability$CurioInventoryWrapper"},transformer:function(c) { return bonsGuarded(c, function(c) {
var methodVisitor, annotationVisitor0, annotationVisitor1, annotationVisitor2, fieldVisitor;
removeMethod(c,"clearCachedSlotModifiers","()V",152);
methodVisitor = new MethodNode(1,"clearCachedSlotModifiers","()V",null,[]);
methodVisitor.visitCode();
var label0 = new Label();
methodVisitor.visitLabel(label0);
methodVisitor.visitLineNumber(597, label0);
methodVisitor.visitInsn(O.ACONST_NULL);
methodVisitor.visitVarInsn(O.ASTORE, 1);
var label1 = new Label();
methodVisitor.visitLabel(label1);
methodVisitor.visitLineNumber(599, label1);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitFieldInsn(O.GETFIELD, "top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "curios", "Ljava/util/Map;");
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(O.ASTORE, 2);
var label2 = new Label();
methodVisitor.visitLabel(label2);
methodVisitor.visitFrame(O.F_APPEND,2, ["java/util/Map", "java/util/Iterator"], 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
var label3 = new Label();
methodVisitor.visitJumpInsn(O.IFEQ, label3);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/util/Map$Entry");
methodVisitor.visitVarInsn(O.ASTORE, 3);
var label4 = new Label();
methodVisitor.visitLabel(label4);
methodVisitor.visitLineNumber(600, label4);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler");
methodVisitor.visitVarInsn(O.ASTORE, 4);
var label5 = new Label();
methodVisitor.visitLabel(label5);
methodVisitor.visitLineNumber(601, label5);
methodVisitor.visitVarInsn(O.ALOAD, 4);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "getCachedModifiers", "()Ljava/util/Set;", true);
methodVisitor.visitVarInsn(O.ASTORE, 5);
var label6 = new Label();
methodVisitor.visitLabel(label6);
methodVisitor.visitLineNumber(603, label6);
methodVisitor.visitVarInsn(O.ALOAD, 5);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "isEmpty", "()Z", true);
var label7 = new Label();
methodVisitor.visitJumpInsn(O.IFNE, label7);
var label8 = new Label();
methodVisitor.visitLabel(label8);
methodVisitor.visitLineNumber(604, label8);
methodVisitor.visitVarInsn(O.ALOAD, 4);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "getStacks", "()Ltop/theillusivec4/curios/api/type/inventory/IDynamicStackHandler;", true);
methodVisitor.visitVarInsn(O.ASTORE, 6);
var label9 = new Label();
methodVisitor.visitLabel(label9);
methodVisitor.visitLineNumber(605, label9);
methodVisitor.visitVarInsn(O.ALOAD, 4);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "getRenders", "()Lnet/minecraft/core/NonNullList;", true);
methodVisitor.visitVarInsn(O.ASTORE, 7);
var label10 = new Label();
methodVisitor.visitLabel(label10);
methodVisitor.visitLineNumber(606, label10);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map$Entry", "getKey", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/lang/String");
methodVisitor.visitVarInsn(O.ASTORE, 8);
var label11 = new Label();
methodVisitor.visitLabel(label11);
methodVisitor.visitLineNumber(608, label11);
methodVisitor.visitInsn(O.ICONST_0);
methodVisitor.visitVarInsn(O.ISTORE, 9);
var label12 = new Label();
methodVisitor.visitLabel(label12);
methodVisitor.visitFrame(O.F_FULL, 10, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Set", "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "net/minecraft/core/NonNullList", "java/lang/String", O.INTEGER], 0, []);
methodVisitor.visitVarInsn(O.ILOAD, 9);
methodVisitor.visitVarInsn(O.ALOAD, 6);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "getSlots", "()I", true);
methodVisitor.visitJumpInsn(O.IF_ICMPGE, label7);
var label13 = new Label();
methodVisitor.visitLabel(label13);
methodVisitor.visitLineNumber(609, label13);
methodVisitor.visitVarInsn(O.ALOAD, 6);
methodVisitor.visitVarInsn(O.ILOAD, 9);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "getStackInSlot", "(I)Lnet/minecraft/world/item/ItemStack;", true);
methodVisitor.visitVarInsn(O.ASTORE, 10);
var label14 = new Label();
methodVisitor.visitLabel(label14);
methodVisitor.visitLineNumber(611, label14);
methodVisitor.visitVarInsn(O.ALOAD, 10);
methodVisitor.visitMethodInsn(O.INVOKEVIRTUAL, "net/minecraft/world/item/ItemStack", "m_41619_", "()Z", false);
var label15 = new Label();
methodVisitor.visitJumpInsn(O.IFNE, label15);
var label16 = new Label();
methodVisitor.visitLabel(label16);
methodVisitor.visitLineNumber(612, label16);
methodVisitor.visitTypeInsn(O.NEW, "top/theillusivec4/curios/api/SlotContext");
methodVisitor.visitInsn(O.DUP);
methodVisitor.visitVarInsn(O.ALOAD, 8);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitMethodInsn(O.INVOKEVIRTUAL, "top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "getWearer", "()Lnet/minecraft/world/entity/LivingEntity;", false);
methodVisitor.visitVarInsn(O.ILOAD, 9);
methodVisitor.visitInsn(O.ICONST_0);
methodVisitor.visitVarInsn(O.ALOAD, 7);
var label17 = new Label();
methodVisitor.visitLabel(label17);
methodVisitor.visitLineNumber(613, label17);
methodVisitor.visitMethodInsn(O.INVOKEVIRTUAL, "net/minecraft/core/NonNullList", "size", "()I", false);
methodVisitor.visitVarInsn(O.ILOAD, 9);
var label18 = new Label();
methodVisitor.visitJumpInsn(O.IF_ICMPLE, label18);
methodVisitor.visitVarInsn(O.ALOAD, 7);
methodVisitor.visitVarInsn(O.ILOAD, 9);
methodVisitor.visitMethodInsn(O.INVOKEVIRTUAL, "net/minecraft/core/NonNullList", "get", "(I)Ljava/lang/Object;", false);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/lang/Boolean");
methodVisitor.visitMethodInsn(O.INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z", false);
methodVisitor.visitJumpInsn(O.IFEQ, label18);
methodVisitor.visitInsn(O.ICONST_1);
var label19 = new Label();
methodVisitor.visitJumpInsn(O.GOTO, label19);
methodVisitor.visitLabel(label18);
methodVisitor.visitFrame(O.F_FULL, 11, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Set", "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "net/minecraft/core/NonNullList", "java/lang/String", O.INTEGER, "net/minecraft/world/item/ItemStack"], 6, [label16, label16, "java/lang/String", "net/minecraft/world/entity/LivingEntity", O.INTEGER, O.INTEGER]);
methodVisitor.visitInsn(O.ICONST_0);
methodVisitor.visitLabel(label19);
methodVisitor.visitFrame(O.F_FULL, 11, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Set", "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "net/minecraft/core/NonNullList", "java/lang/String", O.INTEGER, "net/minecraft/world/item/ItemStack"], 7, [label16, label16, "java/lang/String", "net/minecraft/world/entity/LivingEntity", O.INTEGER, O.INTEGER, O.INTEGER]);
methodVisitor.visitMethodInsn(O.INVOKESPECIAL, "top/theillusivec4/curios/api/SlotContext", "<init>", "(Ljava/lang/String;Lnet/minecraft/world/entity/LivingEntity;IZZ)V", false);
methodVisitor.visitVarInsn(O.ASTORE, 11);
var label20 = new Label();
methodVisitor.visitLabel(label20);
methodVisitor.visitLineNumber(615, label20);
methodVisitor.visitVarInsn(O.ALOAD, 11);
methodVisitor.visitMethodInsn(O.INVOKESTATIC, "top/theillusivec4/curios/api/CuriosApi", "getSlotUuid", "(Ltop/theillusivec4/curios/api/SlotContext;)Ljava/util/UUID;", false);
methodVisitor.visitVarInsn(O.ASTORE, 12);
var label21 = new Label();
methodVisitor.visitLabel(label21);
methodVisitor.visitLineNumber(616, label21);
methodVisitor.visitVarInsn(O.ALOAD, 11);
methodVisitor.visitVarInsn(O.ALOAD, 12);
methodVisitor.visitVarInsn(O.ALOAD, 10);
var label22 = new Label();
methodVisitor.visitLabel(label22);
methodVisitor.visitLineNumber(617, label22);
methodVisitor.visitMethodInsn(O.INVOKESTATIC, "top/theillusivec4/curios/api/CuriosApi", "getAttributeModifiers", "(Ltop/theillusivec4/curios/api/SlotContext;Ljava/util/UUID;Lnet/minecraft/world/item/ItemStack;)Lcom/google/common/collect/Multimap;", false);
methodVisitor.visitVarInsn(O.ASTORE, 13);
var label23 = new Label();
methodVisitor.visitLabel(label23);
methodVisitor.visitLineNumber(619, label23);
methodVisitor.visitVarInsn(O.ALOAD, 13);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "com/google/common/collect/Multimap", "keySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(O.ASTORE, 14);
var label24 = new Label();
methodVisitor.visitLabel(label24);
methodVisitor.visitFrame(O.F_FULL, 15, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Set", "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "net/minecraft/core/NonNullList", "java/lang/String", O.INTEGER, "net/minecraft/world/item/ItemStack", "top/theillusivec4/curios/api/SlotContext", "java/util/UUID", "com/google/common/collect/Multimap", "java/util/Iterator"], 0, []);
methodVisitor.visitVarInsn(O.ALOAD, 14);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
methodVisitor.visitJumpInsn(O.IFEQ, label15);
methodVisitor.visitVarInsn(O.ALOAD, 14);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "net/minecraft/world/entity/ai/attributes/Attribute");
methodVisitor.visitVarInsn(O.ASTORE, 15);
var label25 = new Label();
methodVisitor.visitLabel(label25);
methodVisitor.visitLineNumber(621, label25);
methodVisitor.visitVarInsn(O.ALOAD, 15);
methodVisitor.visitTypeInsn(O.INSTANCEOF, "top/theillusivec4/curios/api/SlotAttribute");
var label26 = new Label();
methodVisitor.visitJumpInsn(O.IFEQ, label26);
methodVisitor.visitVarInsn(O.ALOAD, 15);
methodVisitor.visitTypeInsn(O.CHECKCAST, "top/theillusivec4/curios/api/SlotAttribute");
methodVisitor.visitVarInsn(O.ASTORE, 16);
var label27 = new Label();
methodVisitor.visitLabel(label27);
methodVisitor.visitLineNumber(622, label27);
methodVisitor.visitVarInsn(O.ALOAD, 1);
methodVisitor.visitVarInsn(O.ALOAD, 16);
methodVisitor.visitMethodInsn(O.INVOKEVIRTUAL, "top/theillusivec4/curios/api/SlotAttribute", "getIdentifier", "()Ljava/lang/String;", false);
methodVisitor.visitVarInsn(O.ALOAD, 13);
methodVisitor.visitVarInsn(O.ALOAD, 15);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "com/google/common/collect/Multimap", "get", "(Ljava/lang/Object;)Ljava/util/Collection;", true);
methodVisitor.visitMethodInsn(O.INVOKESTATIC, "top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "ac$collectSlotModifiers", "(Ljava/util/Map;Ljava/lang/String;Ljava/util/Collection;)Ljava/util/Map;", false);
methodVisitor.visitVarInsn(O.ASTORE, 1);
methodVisitor.visitLabel(label26);
methodVisitor.visitLineNumber(624, label26);
methodVisitor.visitFrame(O.F_APPEND,1, ["net/minecraft/world/entity/ai/attributes/Attribute"], 0, null);
methodVisitor.visitJumpInsn(O.GOTO, label24);
methodVisitor.visitLabel(label15);
methodVisitor.visitLineNumber(608, label15);
methodVisitor.visitFrame(O.F_FULL, 11, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Set", "top/theillusivec4/curios/api/type/inventory/IDynamicStackHandler", "net/minecraft/core/NonNullList", "java/lang/String", O.INTEGER, "net/minecraft/world/item/ItemStack"], 0, []);
methodVisitor.visitIincInsn(9, 1);
methodVisitor.visitJumpInsn(O.GOTO, label12);
methodVisitor.visitLabel(label7);
methodVisitor.visitLineNumber(628, label7);
methodVisitor.visitFrame(O.F_FULL, 6, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Set"], 0, []);
methodVisitor.visitJumpInsn(O.GOTO, label2);
methodVisitor.visitLabel(label3);
methodVisitor.visitLineNumber(630, label3);
methodVisitor.visitFrame(O.F_CHOP,3, null, 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 1);
methodVisitor.visitInsn(O.DUP);
var label28 = new Label();
methodVisitor.visitJumpInsn(O.IFNONNULL, label28);
methodVisitor.visitInsn(O.POP);
methodVisitor.visitInsn(O.RETURN);
methodVisitor.visitLabel(label28);
methodVisitor.visitFrame(O.F_SAME1, 0, null, 1, ["java/util/Map"]);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(O.ASTORE, 2);
var label29 = new Label();
methodVisitor.visitLabel(label29);
methodVisitor.visitFrame(O.F_SAME, 0, null, 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
var label30 = new Label();
methodVisitor.visitJumpInsn(O.IFEQ, label30);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/util/Map$Entry");
methodVisitor.visitVarInsn(O.ASTORE, 3);
var label31 = new Label();
methodVisitor.visitLabel(label31);
methodVisitor.visitLineNumber(631, label31);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map$Entry", "getKey", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/lang/String");
methodVisitor.visitVarInsn(O.ASTORE, 4);
var label32 = new Label();
methodVisitor.visitLabel(label32);
methodVisitor.visitLineNumber(632, label32);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitFieldInsn(O.GETFIELD, "top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "curios", "Ljava/util/Map;");
methodVisitor.visitVarInsn(O.ALOAD, 4);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map", "get", "(Ljava/lang/Object;)Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler");
methodVisitor.visitVarInsn(O.ASTORE, 5);
var label33 = new Label();
methodVisitor.visitLabel(label33);
methodVisitor.visitLineNumber(634, label33);
methodVisitor.visitVarInsn(O.ALOAD, 5);
var label34 = new Label();
methodVisitor.visitJumpInsn(O.IFNULL, label34);
var label35 = new Label();
methodVisitor.visitLabel(label35);
methodVisitor.visitLineNumber(636, label35);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/util/Collection");
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Collection", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(O.ASTORE, 6);
var label36 = new Label();
methodVisitor.visitLabel(label36);
methodVisitor.visitFrame(O.F_FULL, 7, ["top/theillusivec4/curios/common/capability/CurioInventoryCapability$CurioInventoryWrapper", "java/util/Map", "java/util/Iterator", "java/util/Map$Entry", "java/lang/String", "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "java/util/Iterator"], 0, []);
methodVisitor.visitVarInsn(O.ALOAD, 6);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
var label37 = new Label();
methodVisitor.visitJumpInsn(O.IFEQ, label37);
methodVisitor.visitVarInsn(O.ALOAD, 6);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "net/minecraft/world/entity/ai/attributes/AttributeModifier");
methodVisitor.visitVarInsn(O.ASTORE, 7);
var label38 = new Label();
methodVisitor.visitLabel(label38);
methodVisitor.visitLineNumber(637, label38);
methodVisitor.visitVarInsn(O.ALOAD, 5);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "getCachedModifiers", "()Ljava/util/Set;", true);
methodVisitor.visitVarInsn(O.ALOAD, 7);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "remove", "(Ljava/lang/Object;)Z", true);
methodVisitor.visitInsn(O.POP);
var label39 = new Label();
methodVisitor.visitLabel(label39);
methodVisitor.visitLineNumber(638, label39);
methodVisitor.visitJumpInsn(O.GOTO, label36);
methodVisitor.visitLabel(label37);
methodVisitor.visitLineNumber(639, label37);
methodVisitor.visitFrame(O.F_SAME, 0, null, 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 5);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "top/theillusivec4/curios/api/type/inventory/ICurioStacksHandler", "clearCachedModifiers", "()V", true);
methodVisitor.visitLabel(label34);
methodVisitor.visitLineNumber(641, label34);
methodVisitor.visitFrame(O.F_CHOP,1, null, 0, null);
methodVisitor.visitJumpInsn(O.GOTO, label29);
methodVisitor.visitLabel(label30);
methodVisitor.visitLineNumber(642, label30);
methodVisitor.visitFrame(O.F_CHOP,3, null, 0, null);
methodVisitor.visitInsn(O.RETURN);
methodVisitor.visitMaxs(8, 17);
methodVisitor.visitEnd();
c.methods.add(methodVisitor);
methodVisitor = new MethodNode(10,"ac$collectSlotModifiers","(Ljava/util/Map;Ljava/lang/String;Ljava/util/Collection;)Ljava/util/Map;","<T:Ljava/lang/Object;>(Ljava/util/Map<Ljava/lang/String;Ljava/util/Set<TT;>;>;Ljava/lang/String;Ljava/util/Collection<TT;>;)Ljava/util/Map<Ljava/lang/String;Ljava/util/Set<TT;>;>;",[]);
methodVisitor.visitCode();
var label0 = new Label();
methodVisitor.visitLabel(label0);
methodVisitor.visitLineNumber(6, label0);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKESTATIC, "java/util/Objects", "requireNonNull", "(Ljava/lang/Object;)Ljava/lang/Object;", false);
methodVisitor.visitInsn(O.POP);
var label1 = new Label();
methodVisitor.visitLabel(label1);
methodVisitor.visitLineNumber(7, label1);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Collection", "isEmpty", "()Z", true);
var label2 = new Label();
methodVisitor.visitJumpInsn(O.IFEQ, label2);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitInsn(O.ARETURN);
methodVisitor.visitLabel(label2);
methodVisitor.visitLineNumber(8, label2);
methodVisitor.visitFrame(O.F_SAME, 0, null, 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 0);
var label3 = new Label();
methodVisitor.visitJumpInsn(O.IFNONNULL, label3);
methodVisitor.visitIntInsn(O.BIPUSH, 12);
methodVisitor.visitMethodInsn(O.INVOKESTATIC, "com/google/common/collect/Maps", "newHashMapWithExpectedSize", "(I)Ljava/util/HashMap;", false);
methodVisitor.visitVarInsn(O.ASTORE, 0);
methodVisitor.visitLabel(label3);
methodVisitor.visitLineNumber(9, label3);
methodVisitor.visitFrame(O.F_SAME, 0, null, 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitVarInsn(O.ALOAD, 1);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map", "get", "(Ljava/lang/Object;)Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(O.CHECKCAST, "java/util/Set");
methodVisitor.visitVarInsn(O.ASTORE, 3);
var label4 = new Label();
methodVisitor.visitLabel(label4);
methodVisitor.visitLineNumber(10, label4);
methodVisitor.visitVarInsn(O.ALOAD, 3);
var label5 = new Label();
methodVisitor.visitJumpInsn(O.IFNONNULL, label5);
methodVisitor.visitInsn(O.ICONST_2);
methodVisitor.visitMethodInsn(O.INVOKESTATIC, "com/google/common/collect/Sets", "newHashSetWithExpectedSize", "(I)Ljava/util/HashSet;", false);
methodVisitor.visitVarInsn(O.ASTORE, 3);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "addAll", "(Ljava/util/Collection;)Z", true);
var label6 = new Label();
methodVisitor.visitJumpInsn(O.IFEQ, label6);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitVarInsn(O.ALOAD, 1);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Map", "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", true);
methodVisitor.visitInsn(O.POP);
methodVisitor.visitJumpInsn(O.GOTO, label6);
methodVisitor.visitLabel(label5);
methodVisitor.visitLineNumber(11, label5);
methodVisitor.visitFrame(O.F_APPEND,1, ["java/util/Set"], 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 3);
methodVisitor.visitVarInsn(O.ALOAD, 2);
methodVisitor.visitMethodInsn(O.INVOKEINTERFACE, "java/util/Set", "addAll", "(Ljava/util/Collection;)Z", true);
methodVisitor.visitInsn(O.POP);
methodVisitor.visitLabel(label6);
methodVisitor.visitLineNumber(12, label6);
methodVisitor.visitFrame(O.F_SAME, 0, null, 0, null);
methodVisitor.visitVarInsn(O.ALOAD, 0);
methodVisitor.visitInsn(O.ARETURN);
methodVisitor.visitMaxs(3, 4);
methodVisitor.visitEnd();
c.methods.add(methodVisitor);
return c;
}); }}};}
